/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a client session
         * @description Creates a pending client session that will be linked to a user after authentication.
         */
        post: operations["postAuthSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session/status/{clientSessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream client session status
         * @description Server-Sent Events stream that emits session state every 500 ms. Closes when the session is consumed or expires.
         */
        get: operations["getAuthSessionStatusByClientSessionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect to Google OAuth
         * @description Redirects the user to the Google OAuth consent screen.
         */
        get: operations["getAuthGoogle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect to GitHub OAuth
         * @description Redirects the user to the GitHub OAuth consent screen.
         */
        get: operations["getAuthGithub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send email verification code */
        post: operations["postAuthEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email code */
        post: operations["postAuthEmailVerifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with a Stellar wallet */
        post: operations["postAuthWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a ready client session for tokens
         * @description Finalizes authentication. The session must be in ready state.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application config
         * @description Returns the public configuration and branding for the application.
         */
        get: operations["getApplicationsConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application logo
         * @description Returns the application logo as a binary image.
         */
        get: operations["getApplicationsByIdLogo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tx/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build unsigned payment transaction
         * @description Builds an unsigned XDR for a native XLM payment. Client must sign and submit via POST /tx/submit.
         */
        post: operations["postTxBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tx/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit signed transaction
         * @description Submits a signed transaction envelope to the Stellar network.
         */
        post: operations["postTxSubmit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tx/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction status
         * @description Returns transaction status by hash. PENDING = not yet confirmed in Horizon.
         */
        get: operations["getTxStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_API_HEALTH_OK";
                        /** @constant */
                        success: true;
                        content: {
                            /** @constant */
                            status: "ok";
                            version: string;
                        };
                    };
                };
            };
        };
    };
    postAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_SESSION_CREATED";
                        /** @constant */
                        success: true;
                        content: {
                            clientSessionId: string;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getAuthSessionStatusByClientSessionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of session status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        status: string;
                        user: {
                            id?: string;
                            ready: boolean;
                        };
                        data: {
                            mail: string;
                            first_name: string;
                            last_name: string;
                            avatar: string;
                            providers: {
                                email: {
                                    address: string;
                                } | null;
                                google: {
                                    id: string;
                                } | null;
                                github: {
                                    id: string;
                                } | null;
                                wallet: {
                                    address: string;
                                } | null;
                            };
                        };
                    };
                };
            };
        };
    };
    getAuthGoogle: {
        parameters: {
            query: {
                api_key: string;
                client_session_id: string;
                redirect_uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getAuthGithub: {
        parameters: {
            query: {
                api_key: string;
                client_session_id: string;
                redirect_uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to GitHub OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postAuthEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    clientSessionId: string;
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Code sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_EMAIL_CODE_SENT";
                        /** @constant */
                        success: true;
                        content: {
                            clientSessionId: string;
                            email: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postAuthEmailVerifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    clientSessionId: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Code verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_EMAIL_CODE_VERIFIED";
                        /** @constant */
                        success: true;
                        content: {
                            clientSessionId: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postAuthWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    clientSessionId: string;
                    walletAddress: string;
                };
            };
        };
        responses: {
            /** @description Wallet authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_WALLET_AUTHENTICATED";
                        /** @constant */
                        success: true;
                        content: {
                            clientSessionId: string;
                            walletAddress: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    clientSessionId: string;
                };
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_LOGIN_SUCCESS";
                        /** @constant */
                        success: true;
                        content: {
                            clientSessionId: string;
                            userId: string | null;
                            status: string;
                            token: {
                                accessToken: string;
                                refreshToken: string;
                                expiresAt: number;
                            };
                            user: {
                                id?: string;
                                ready: boolean;
                            };
                            wallet: {
                                publicKey: string | null;
                                existsOnStellar?: boolean;
                                createdAt?: number;
                            };
                            data: {
                                mail: string;
                                first_name: string;
                                last_name: string;
                                avatar: string;
                                providers: {
                                    email: {
                                        address: string;
                                    } | null;
                                    google: {
                                        id: string;
                                    } | null;
                                    github: {
                                        id: string;
                                    } | null;
                                    wallet: {
                                        address: string;
                                    } | null;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getApplicationsConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_APPLICATION_CONFIG";
                        /** @constant */
                        success: true;
                        content: {
                            application: {
                                name: string;
                            };
                            styles: {
                                theme?: string;
                                accentColor?: string;
                                logoUrl?: string;
                                emailEnabled?: boolean;
                                embeddedWallets?: boolean;
                                providers?: {
                                    google?: boolean;
                                    discord?: boolean;
                                    x?: boolean;
                                    github?: boolean;
                                    apple?: boolean;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getApplicationsByIdLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logo image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postTxBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    network: "testnet" | "mainnet";
                    publicKey: string;
                    /** @constant */
                    operation: "payment";
                    params: {
                        destination: string;
                        amount: string;
                        asset: {
                            /** @constant */
                            type: "native";
                        } | {
                            /** @constant */
                            type: "credit_alphanum4";
                            code: string;
                            issuer: string;
                        };
                    };
                    options?: {
                        timeoutSec?: number;
                        memo?: {
                            /** @constant */
                            type: "text";
                            value: string;
                        } | {
                            /** @constant */
                            type: "id";
                            value: string;
                        };
                    };
                };
            };
        };
        responses: {
            /** @description Unsigned XDR and summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_TX_BUILD";
                        /** @constant */
                        success: true;
                        content: {
                            unsignedXdr: string;
                            networkPassphrase: string;
                            estimatedFee: string;
                            summary: {
                                title: string;
                                lines: string[];
                                network: string;
                                fee: string;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Horizon error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    postTxSubmit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submit result (PENDING | SUCCESS | FAILED) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_TX_SUBMIT";
                        /** @constant */
                        success: true;
                        content: {
                            hash: string;
                            /** @enum {string} */
                            status: "PENDING" | "SUCCESS" | "FAILED";
                            resultCode?: string;
                            message?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getTxStatus: {
        parameters: {
            query: {
                network: "testnet" | "mainnet";
                hash: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction status (PENDING si no existe aún en Horizon) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "SDK_TX_STATUS";
                        /** @constant */
                        success: true;
                        content: {
                            hash: string;
                            /** @enum {string} */
                            status: "PENDING" | "SUCCESS" | "FAILED";
                            resultCode?: string;
                            ledger?: number;
                            message?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
}
