export const StateStatus = {
  NONE: 'NONE',
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
export type StateStatus = (typeof StateStatus)[keyof typeof StateStatus];

export const PollarStateVar = {
  AUTHENTICATION: 'authentication',
  TRANSACTION: 'transaction',
} as const;

export type PollarStateVar = (typeof PollarStateVar)[keyof typeof PollarStateVar];

export const STATE_VAR_CODES = {
  authentication: {
    NONE: 'NONE',
    LOGOUT: 'LOGOUT',
    CREATE_SESSION_START: 'CREATE_SESSION_START',
    CREATE_SESSION_ERROR: 'CREATE_SESSION_ERROR',
    CREATE_SESSION_SUCCESS: 'CREATE_SESSION_SUCCESS',
    EMAIL_AUTH_START: 'EMAIL_AUTH_START',
    EMAIL_AUTH_START_ERROR: 'EMAIL_AUTH_START_ERROR',
    EMAIL_AUTH_START_SUCCESS: 'EMAIL_AUTH_START_SUCCESS',
    EMAIL_AUTH_CODE_ERROR: 'EMAIL_AUTH_CODE_ERROR',
    EMAIL_AUTH_CODE_SUCCESS: 'EMAIL_AUTH_CODE_SUCCESS',
    WALLET_AUTH_START: 'WALLET_AUTH_START',
    WALLET_AUTH_FREIGHTER_NOT_INSTALLED: 'WALLET_AUTH_FREIGHTER_NOT_INSTALLED',
    WALLET_AUTH_ALBEDO_NOT_INSTALLED: 'WALLET_AUTH_ALBEDO_NOT_INSTALLED',
    WALLET_AUTH_CONNECTED: 'WALLET_AUTH_CONNECTED',
    WALLET_AUTH_LOGIN_START: 'WALLET_AUTH_LOGIN_START',
    WALLET_AUTH_LOGIN_START_SUCCESS: 'WALLET_AUTH_LOGIN_START_SUCCESS',
    WALLET_AUTH_LOGIN_START_ERROR: 'WALLET_AUTH_LOGIN_START_ERROR',
    WALLET_AUTH_ERROR: 'WALLET_AUTH_ERROR',
    STREAM_POLL_START: 'STREAM_POLL_START',
    STREAM_POLL_EVENT: 'STREAM_POLL_EVENT',
    STREAM_POLL_READY: 'STREAM_POLL_READY',
    FETCH_SESSION_START: 'FETCH_SESSION_START',
    FETCH_SESSION_SUCCESS: 'FETCH_SESSION_SUCCESS',
    FETCH_SESSION_ERROR: 'FETCH_SESSION_ERROR',
    RESTORED_SESSION_SUCCESS: 'RESTORED_SESSION_SUCCESS',
    RESTORED_SESSION_ERROR: 'RESTORED_SESSION_ERROR',
    SESSION_STORED: 'SESSION_STORED',
    ERROR_ABORTED: 'ABORTED',
    ERROR_UNKNOWN: 'ERROR_UNKNOWN',
  },
  walletAddress: {
    NONE: 'NONE',
    REMOVED_ADDRESS: 'REMOVED_ADDRESS',
    UPDATED_ADDRESS: 'UPDATED_ADDRESS',
  },
  transaction: {
    NONE: 'NONE',
    BUILD_TRANSACTION_ERROR_NO_WALLET: 'BUILD_TRANSACTION_ERROR_NO_WALLET',
    BUILD_TRANSACTION_START: 'BUILD_TRANSACTION_START',
    BUILD_TRANSACTION_SUCCESS: 'BUILD_TRANSACTION_SUCCESS',
    BUILD_TRANSACTION_ERROR: 'BUILD_TRANSACTION_ERROR',
    SIGN_TRANSACTION_START: 'SIGN_TRANSACTION_START',
    SIGN_TRANSACTION_SUCCESS: 'SIGN_TRANSACTION_SUCCESS',
    SIGN_TRANSACTION_ERROR: 'SIGN_TRANSACTION_ERROR',
    SEND_TRANSACTION_START: 'SEND_TRANSACTION_START',
    SEND_TRANSACTION_SUCCESS: 'SEND_TRANSACTION_SUCCESS',
    SEND_TRANSACTION_ERROR: 'SEND_TRANSACTION_ERROR',
  },
} as const;
